/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:5
-- pgrx_validation::hello_pgrx_validation
CREATE  FUNCTION "hello_pgrx_validation"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_pgrx_validation_wrapper';
/* </end connected objects> */

